# Generated by Django 3.2.3 on 2021-05-17 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainapp', '0015_auto_20200730_1041'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='final_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, verbose_name='Umumiy narx'),
        ),
        migrations.AlterField(
            model_name='cart',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mainapp.customer', verbose_name='Egasi'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Turkum nomi'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Manzil'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='orders',
            field=models.ManyToManyField(related_name='related_order', to='mainapp.Order', verbose_name='Xaridorlarning buyurtmalari'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefon raqami'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Turkum'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='description',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='diagonal',
            field=models.CharField(max_length=255, verbose_name='Diagonal'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='display_type',
            field=models.CharField(max_length=255, verbose_name='Displey turi'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='processor_freq',
            field=models.CharField(max_length=255, verbose_name='CPU chastotasi'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='ram',
            field=models.CharField(max_length=255, verbose_name='Operativ xotira'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='time_without_charge',
            field=models.CharField(max_length=255, verbose_name='Batareya quvvati'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ism'),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='video',
            field=models.CharField(max_length=255, verbose_name='Video karta'),
        ),
        migrations.AlterField(
            model_name='order',
            name='address',
            field=models.CharField(blank=True, max_length=1024, null=True, verbose_name='Manzilingiz'),
        ),
        migrations.AlterField(
            model_name='order',
            name='buying_type',
            field=models.CharField(choices=[('self', 'Olib ketish'), ('delivery', 'Yetkazib berish')], default='self', max_length=100, verbose_name='Buyurtma turi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, null=True, verbose_name='Buyurtmani sharhlang'),
        ),
        migrations.AlterField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Buyurtmani yaratish sanasi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='first_name',
            field=models.CharField(max_length=255, verbose_name='Ismingiz'),
        ),
        migrations.AlterField(
            model_name='order',
            name='last_name',
            field=models.CharField(max_length=255, verbose_name='Familyangiz'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='Buyurtmani olgan sana'),
        ),
        migrations.AlterField(
            model_name='order',
            name='phone',
            field=models.CharField(max_length=20, verbose_name='Telefon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('new', 'Yangi buyurtma'), ('in_progress', 'Qayta ishlashda buyurtma'), ('is_ready', 'Buyurtma tayyor'), ('completed', 'Buyurtma tugadi')], default='new', max_length=100, verbose_name='Buyurtma holati'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='accum_volume',
            field=models.CharField(max_length=255, verbose_name='Batareya hajmi'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.category', verbose_name='Turkum'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='description',
            field=models.TextField(null=True, verbose_name='Tavsif'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='diagonal',
            field=models.CharField(max_length=255, verbose_name='Diagonal'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='display_type',
            field=models.CharField(max_length=255, verbose_name='Displey turi'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='frontal_cam_mp',
            field=models.CharField(max_length=255, verbose_name='Old kamera (MP)'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='Rasm'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='main_cam_mp',
            field=models.CharField(max_length=255, verbose_name='Asosiy kamera'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Narx'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='ram',
            field=models.CharField(max_length=255, verbose_name='Operativ xotira'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='resolution',
            field=models.CharField(max_length=255, verbose_name='Ekran o`lchamlari'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd',
            field=models.BooleanField(default=True, verbose_name='SD-kartaning mavjudligi'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='sd_volume_max',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Maksimal o`rnatilgan xotira'),
        ),
        migrations.AlterField(
            model_name='smartphone',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Ism'),
        ),
    ]
